
/*
 * BotonesSuperioresPanel.java
 *
 * Created on 21-ago-2010, 20:29:24
 */

package Vista.PanelesPrincipal;

import Vista.Icons;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.ImageIcon;

/**
 * Clase que genera y gestiona el panel que presenta los botones que se encuentran
 * en la parte superior de la pantalla principal
 * @author Javier Rascón Mesa
 */
public class BotonesSuperioresPanel extends javax.swing.JPanel {

    /*---- Atributos ----*/

    /**
     * Lista d elos observadores de la pulsación del botón de nueva nota
     */
    LinkedList<ActionListener> _llNuevaNota;

    /**
     * Lista d elos observadores de la pulsación del botón de deshacer
     */
    LinkedList<ActionListener> _llUndo;

    /**
     * Lista d elos observadores de la pulsación del botón de rehacer
     */
    LinkedList<ActionListener> _llRedo;

    /**
     * Lista d elos observadores de la pulsación del botón de nuevo destinatario
     */
    LinkedList<ActionListener> _llNuevoDest;

    /**
     * Lista d elos observadores de la pulsación del botón de modificar
     * destinatario
     */
    LinkedList<ActionListener> _llModDest;

    /**
     * Lista d elos observadores de la pulsación del botón de eliminar
     * destinatario
     */
    LinkedList<ActionListener> _llElimDest;

    /*---- Métodos ----*/

    /**
     * Constructor
     */
    public BotonesSuperioresPanel() {
        initComponents();
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón nueva
     * nota
     * @param al Observador de la pulsación del botón nueva nota
     */
    public void addNuevaNotaButtonListener(ActionListener al){
        _llNuevaNota.add(al);
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón deshacer
     * @param al Observador de la pulsación del botón deshacer
     */
    public void addUndoButtonListener(ActionListener al){
        _llUndo.add(al);
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón rehacer
     * @param al Observador de la pulsación del botón rehacer
     */
    public void addRedoButtonListener(ActionListener al){
        _llRedo.add(al);
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón nuevo
     * destinatario
     * @param al Observador de la pulsación del botón nuevo destinatario
     */
    public void addNuevoDestinatarioButtonListener(ActionListener al){
        _llNuevoDest.add(al);
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón
     * modificar destinatario
     * @param al Observador de la pulsación del botón modificar destinatario
     */
    public void addModificarDestinatarioButtonListener(ActionListener al){
        _llModDest.add(al);
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón eliminar
     * destinatario
     * @param al Observador de la pulsación del botón eliminar destinatario
     */
    public void addEliminarDestinatarioButtonListener(ActionListener al){
        _llElimDest.add(al);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _nuevaNotaButton = new javax.swing.JButton();
        _undoButton = new javax.swing.JButton();
        _redoButton = new javax.swing.JButton();
        _nuevoDestButton = new javax.swing.JButton();
        _modDestButton = new javax.swing.JButton();
        _eliminarDestButton = new javax.swing.JButton();

        setBorder(null);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        _nuevaNotaButton.setIcon(new ImageIcon(Icons.getIconNewNote()));
        _nuevaNotaButton.setToolTipText("Nueva nota");
        _nuevaNotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _nuevaNotaButtonActionPerformed(evt);
            }
        });
        add(_nuevaNotaButton);

        _undoButton.setIcon(new ImageIcon(Icons.getIconUndo()));
        _undoButton.setToolTipText("Deshacer");
        _undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _undoButtonActionPerformed(evt);
            }
        });
        add(_undoButton);

        _redoButton.setIcon(new ImageIcon(Icons.getIconRedo()));
        _redoButton.setToolTipText("Rehacer");
        _redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _redoButtonActionPerformed(evt);
            }
        });
        add(_redoButton);

        _nuevoDestButton.setIcon(new ImageIcon(Icons.getIconAddDest()));
        _nuevoDestButton.setToolTipText("Nuevo destinatario");
        _nuevoDestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _nuevoDestButtonActionPerformed(evt);
            }
        });
        add(_nuevoDestButton);

        _modDestButton.setIcon(new ImageIcon(Icons.getIconEditDest()));
        _modDestButton.setToolTipText("Modificar destinatario");
        _modDestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _modDestButtonActionPerformed(evt);
            }
        });
        add(_modDestButton);

        _eliminarDestButton.setIcon(new ImageIcon(Icons.getIconDeleteDest()));
        _eliminarDestButton.setToolTipText("Eliminar destinatario");
        _eliminarDestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _eliminarDestButtonActionPerformed(evt);
            }
        });
        add(_eliminarDestButton);
    }// </editor-fold>//GEN-END:initComponents

    private void _nuevaNotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__nuevaNotaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__nuevaNotaButtonActionPerformed

    private void _undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__undoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__undoButtonActionPerformed

    private void _redoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__redoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__redoButtonActionPerformed

    private void _nuevoDestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__nuevoDestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__nuevoDestButtonActionPerformed

    private void _modDestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__modDestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__modDestButtonActionPerformed

    private void _eliminarDestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__eliminarDestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__eliminarDestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _eliminarDestButton;
    private javax.swing.JButton _modDestButton;
    private javax.swing.JButton _nuevaNotaButton;
    private javax.swing.JButton _nuevoDestButton;
    private javax.swing.JButton _redoButton;
    private javax.swing.JButton _undoButton;
    // End of variables declaration//GEN-END:variables

}
