
/*
 * BotonesSuperioresPanel.java
 *
 * Created on 21-ago-2010, 20:29:24
 */

package vista.PanelesPrincipal;

import controlador.undo.ObservadorPilaDeshacer;
import controlador.undo.PilaDeshacer;
import java.awt.event.ActionEvent;
import vista.Icons;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 * Clase que genera y gestiona el panel que presenta los botones que se encuentran
 * en la parte superior de la pantalla principal
 * @author Javier Rascón Mesa
 */
public class BotonesSuperioresPanel extends javax.swing.JPanel {

    /*---- Atributos ----*/

    /*---- Métodos ----*/

    /**
     * Constructor
     */
    public BotonesSuperioresPanel() {
        initComponents();

        PilaDeshacer.registrarObservadorPilaDeshacer(new ObservadorPilaDeshacer() {

            public void pilaDeshacerCambiada() {
                pilaDeshacerCambiada();
            }
        });

        _undoButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
               PilaDeshacer.undo();
            }
        });

        _redoButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
               PilaDeshacer.redo();
            }
        });
    }

    /**
     * Método para añadir un nuevo observador de la pulsación del botón nueva
     * nota
     * @param al Observador de la pulsación del botón nueva nota
     */
    public void addNuevaNotaButtonListener(ActionListener al){
        _nuevaNotaButton.addActionListener(al);
    }

    /**
     * Método que se ejecuta cuando la pila de deshacer se ha modificado
     */
    private void pilaDeshacerCambiada(){
        _undoButton.setEnabled(PilaDeshacer.puedeDeshacer());
        _undoButton.setToolTipText(PilaDeshacer.nombreDeshacer());

        _redoButton.setToolTipText(PilaDeshacer.nombreRehacer());
        _redoButton.setEnabled(PilaDeshacer.puedeRehacer());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _nuevaNotaButton = new javax.swing.JButton();
        _undoButton = new javax.swing.JButton();
        _redoButton = new javax.swing.JButton();

        setBorder(null);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        _nuevaNotaButton.setIcon(new ImageIcon(Icons.getIconNewNote()));
        _nuevaNotaButton.setToolTipText("Nueva nota");
        add(_nuevaNotaButton);

        _undoButton.setIcon(new ImageIcon(Icons.getIconUndo()));
        _undoButton.setToolTipText("Deshacer");
        _undoButton.setEnabled(false);
        _undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _(evt);
            }
        });
        add(_undoButton);

        _redoButton.setIcon(new ImageIcon(Icons.getIconRedo()));
        _redoButton.setToolTipText("Rehacer");
        _redoButton.setEnabled(false);
        add(_redoButton);
    }// </editor-fold>//GEN-END:initComponents

    private void _(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__
        // TODO add your handling code here:
    }//GEN-LAST:event__


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _nuevaNotaButton;
    private javax.swing.JButton _redoButton;
    private javax.swing.JButton _undoButton;
    // End of variables declaration//GEN-END:variables

}
