
/*
 * ResultadosBusquedaPanel.java
 *
 * Created on 22-ago-2010, 17:57:47
 */

package vista.PanelesPrincipal;

import modelo.*;
import vista.TableModels.ResultadosBusquedaTableModel;
import java.awt.event.MouseListener;
import java.util.*;
import javax.swing.JTable;

/**
 * Clase que se encarga de mostrar y gestionar los resultados de las búsquedas
 * realizadas sobre las notas
 * @author Javier Rascón Mesa
 */
public class ResultadosBusquedaPanel extends javax.swing.JPanel {

    /* Atributos */

    /**
     * Atributo para almacenar los datos que se muestran en la tabla
     */
    ResultadosBusquedaTableModel _datosTabla;

    /* Métodos */

    /**
     * Constructor
     */
    public ResultadosBusquedaPanel() {

        _datosTabla = new ResultadosBusquedaTableModel();

        initComponents();

    }

    /**
     * Método para obtener la nota de la fila seleccionada
     * @return Nota de la fila seleccionada
     */
    public Nota getSelectedNota(){
        return _datosTabla.getNotaAt(_resBusqTable.getSelectedRow());
    }

    /**
     * Método para refrescar los datos de la tabla
     * @param datos Lista de notas con los datos actualizados
     */
    public void refrescarDatos(List<Nota> datos){
        _datosTabla.refrescarDatos(datos);
    }

    /**
     * Método para añadir un observador que sea notificado de que se ha hecho
     * click sobre la tabla
     * @param ml obsevador que será notificado de que se ha hecho click sobre la
     * tabla
     */
    public void addClickTablaListener(MouseListener ml){
        _resBusqTable.addMouseListener(ml);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _resBusqScrollPane = new javax.swing.JScrollPane();
        _resBusqTable = new JTable(_datosTabla);

        setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados búsqueda"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        _resBusqScrollPane.setPreferredSize(new java.awt.Dimension(350, 200));
        _resBusqScrollPane.setViewportView(_resBusqTable);

        add(_resBusqScrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane _resBusqScrollPane;
    private javax.swing.JTable _resBusqTable;
    // End of variables declaration//GEN-END:variables

}
